DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `viewAttendanceDatesP`(crn int)
BEGIN
	SELECT ATTENDANCE_DATETIME, ATTENDANCE_ID FROM ATTENDANCE WHERE COURSE_CRN=crn ORDER BY ATTENDANCE_DATETIME ASC;
END
// DELIMITER ;